# Grafana 데이터소스 자동 프로비저닝
# Grafana 시작 시 Prometheus를 자동으로 데이터소스로 등록
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
